# Generated by Django 5.2.8 on 2025-11-30 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia_app', '0002_solicitud_datos_formulario_solicitudhistorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='form_schema',
            field=models.JSONField(blank=True, default=list, help_text='Esquema del formulario dinámico (lista de campos)'),
        ),
    ]
