# Generated by Django 5.2.8 on 2025-11-30 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia_app', '0003_servicio_form_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='segmento',
            field=models.CharField(choices=[('cartech', 'Cartech'), ('foodtech', 'Foodtech'), ('agetech', 'Agetech')], default='cartech', max_length=20),
        ),
    ]
