# Generated by Django 5.2.8 on 2025-11-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia_app', '0004_servicio_segmento'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='ubicacion',
            field=models.TextField(default='Sin especificar', help_text='Dirección o ubicación donde se necesita el servicio'),
        ),
    ]
